config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {registrations: "users_devise/registrations"}

  resources :users, only: [:show] do
    resources :reviews, except: [:index, :show]
  end

  root "pages#show", static: "home"
  get "/pages/*static" => "pages#show", as: :page

  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

  get "tags/:tag", to: "posts#index", as: :tag

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  resources :notifications, only: [:index, :show]

  resources :chat, only: [:index]
  resources :conversations, only: [:create, :destroy]

  get "*path", to: redirect("/")
end

app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit ->{NotificationBroadcastJob.perform_later(self)}

  belongs_to :notified_by, class_name: User.name
  belongs_to :user
  belongs_to :notificationable, polymorphic: true

  enum read: [:unread, :read]
  enum checked: [:uncheck, :checked]

  scope :order_by_created, (->{order created_at: :desc})
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :find_notification, only: :show

  def index
    current_user.notifications.map(&:checked!)
  end

  def show
    @notification.read!
    post = @notification.notificationable
    redirect_to post
  end

  private
  def find_notification
    @notification = Notification.find_by id: params[:id]
    redirect_to root_url, notice: t("not_found") unless @notification
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def noti notification
    post = notification.notificationable
    notification.notified_by.profile.name + t("has-" + notification
      .notice_type) + post.title
  end

  def number
    user_signed_in? ? current_user.notifications.uncheck.count : 0
  end
end

app/views/notifications/_notification.html.erb
<li class = "notification <%= notification.read %>">
  <%= link_to noti(notification), notification, method: :get %>
</li>

app/views/notifications/_notifications.html.erb
<%= link_to notifications_path, class: "dropdown-toggle", id: "noti-count",
  data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"},
  remote: true do %>
  <span class="glyphicon glyphicon-bell"></span>
  <span class="notification-number"><%= number %></span>
  <span class="caret"></span>
<% end %>
<ul class="dropdown-menu dropdown-notification scroll" id="notifications">
  <% current_user.notifications.order_by_created.each do |notification| %>
    <%= render "notifications/notification", notification: notification %>
  <% end %>
</ul>

app/views/notifications/index.js.erb
$('.notification-dropdown').html('<%= j render "notifications/notifications" %>');