config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {registrations: "users_devise/registrations"}

  resources :users, only: [:show] do
    resources :reviews, except: [:index, :show]
  end

  root "pages#show", static: "home"
  get "/pages/*static" => "pages#show", as: :page

  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

  get "tags/:tag", to: "posts#index", as: :tag

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  resources :notifications, only: [:index, :show]

  resources :chat, only: [:index]
  resources :conversations, only: [:create, :destroy]

  get "*path", to: redirect("/")
end

app/views/shared/_sign_in_modal.html.erb
<div class="modal fade" id="sign_in" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
        </button>
        <h4 class="modal-title"><%= t "devise.sessions.title" %></h4>
      </div>
      <div class="modal-body">
        <%= render "devise/shared/user_form", url: session_path(:user),
          action: "login" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t "close" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sign_up_modal.html.erb
<div class="modal fade" id="sign_up" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
        </button>
        <h4 class="modal-title"><%= t "devise.registrations.title" %></h4>
      </div>
      <div class="modal-body">
        <%= render "devise/shared/user_form", url: registration_path(:user),
          action: "register" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t "close" %>
        </button>
      </div>
    </div>
  </div>
</div>