config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {registrations: "users_devise/registrations"}

  resources :users, only: [:show] do
    resources :reviews, except: [:index, :show]
  end

  root "pages#show", static: "home"
  get "/pages/*static" => "pages#show", as: :page

  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

  get "tags/:tag", to: "posts#index", as: :tag

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  resources :notifications, only: [:index, :show]

  resources :chat, only: [:index]
  resources :conversations, only: [:create, :destroy]

  get "*path", to: redirect("/")
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: [:opened, :closed]

  is_impressionable
  acts_as_taggable

  has_many :notifications, as: :notificationable
  has_many :comments, dependent: :destroy
  belongs_to :user

  scope :order_by_created, (->{order created_at: :desc})
  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true
  validates :post_img, attachment_presence: true
  has_attached_file :post_img, styles: {post_index: "250x350>",
    post_show: "147x196>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :post_img, content_type: /\Aimage\/.*\Z/

  acts_as_votable
  searchkick word_middle: [:title, :content]

  def search_data
    {
      title: title,
      content: content,
      tag: tag_list
    }
  end
end

app/models/supports/post.rb
class Supports::Post
  attr_reader :post, :posts

  def initialize post
    @post = post
  end

  def posts
    @posts ||= Post.all
  end

  def last_7_days
    @last_7_days ||= Post.group_by_day(:created_at, last: 7).count
  end

  def last_30_days
    @last_30_days ||= Post.group_by_day(:created_at, last: 30).count
  end

  def last_6_months
    @last_6_months ||= Post.group_by_month(:created_at, last: 6).count
  end

  def most_views_today
    posts
      .sort_by{|post| post.impressionist_count start_date: 1.day.ago}
      .reverse.first(10)
  end

  def most_views_week_ago
    posts
      .sort_by{|post| post.impressionist_count start_date: 7.days.ago}
      .reverse.first(10)
  end

  def most_views_month_ago
    posts
      .sort_by{|post| post.impressionist_count start_date: 1.month.ago}
      .reverse.first(10)
  end

  def comment
    @comment = Comment.new
  end

  def comments_tree
    @comments = @post.comments
  end

  def search
    search = Post.search(params[:q])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @supports = Supports::Post.new @post
    @posts = @posts.page params[:page]
  end

  def destroy
    @post.destroy
    flash[:success] = t "admin.posts.delete.post_deleted"
    redirect_to admin_posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  load_and_authorize_resource

  def index
    @posts =
      if user_signed_in? && params[:tag].nil?
        current_user.posts.order_by_created.page(params[:page]).per(20)
      elsif params[:tag]
        Post.all.tagged_with(params[:tag])
          .order_by_created.page(params[:page]).per(20)
      else
        Post.all.order_by_created.page(params[:page]).per(20)
      end
  end

  def new
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @supports = Supports::Post.new @post
    @conversation = Conversation.where(sender_id: current_user.id,
      recipient_id: @post.user.id).first
    impressionist @post
  end

  def edit
  end

  def update
    if @post.update_attributes post_params
      redirect_to post_path @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit :title,
      :content, :post_img, :tag_list, :status, :price
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def change_post_status post
    if post.closed?
      "opened"
    else
      "closed"
    end
  end
end

app/views/posts/_close_post.html.erb
<%= form_for post do |f| %>
  <%= f.hidden_field :status, value: change_post_status(post) %>
  <%= f.submit t("posts.show.change"), class: "btn btn-primary" %>
<% end %>

app/views/posts/_edit_post_modal.html.erb
<div class="modal fade" id="edit-post-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"></button>
        <h4 class="modal-title"><%= t "posts.show.edit" %></h4>
      </div>
      <div class="modal-body">
        <%= render "posts/post_form", post: post %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t "close" %>
        </button>
      </div>
    </div>

  </div>
</div>

app/views/posts/_post.html.erb
<div class="col-sm-3">
  <div class="col-item">
      <div class="photo">
        <div class="<%= "sold" if post.closed? %>">
          <%= link_to image_tag(post.post_img.url,
            class: "post-image img-responsive #{'watermark' if post.closed?}"),
            post_path(post) %>
        </div>
      </div>
      <div class="info">
        <div class="separator clear-left">
          <p class="btn-add">
          <h5><%= link_to post.title, post_path(post.id) %></h5>
            <%= post.impressionist_count %>views
          </p>
          <p class="btn-details">
            <h5 class="price-text-color">$<%= post.price %></h5>
          </p>
        </div>
          <div class="clearfix">
        </div>
    </div>
  </div>
</div>

app/views/posts/_post_form.html.erb
<div class="col-md-9 col-md-offset-2">
  <div class="post-form">
    <%= form_for post, html: {multipart: true} do |f| %>

      <div class="form-group">
        <%= f.file_field :post_img, accept: "image/jpeg,image/gif,image/png" %>
      </div>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control",
          required: true %>
      </div>

      <div class="form-group">
        <%= f.label :price, t("posts.post_form.price") %>
        <%= f.number_field :price, class: "form-control", required: true,
          step: 0.01 %>
      </div>

      <div class="form-group">
        <%= f.label :content, t("posts.post_form.descrip") %>
        <%= f.cktext_area :content, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :tags %>
        <%= f.text_field :tag_list, class: "form-control" %>
      </div>

      <div class="form-group">
        <div class="actions">
          <%= f.submit yield(:button_text), class: "btn form-control" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_report_form.html.erb
<div id="report_form">
  <% if user_signed_in? %>
    <% if current_user.voted_down_on? post, vote_scope: "report" %>
      <%= t "reports.reported" %>
    <% else %>
      <%= link_to t("reports.report"), post_reports_path(post), method: :post, remote: true,
        data: {confirm: t("admin.posts.index.sure?")} %>
    <% end %>
  <% end %>
  <%= @post.get_downvotes(vote_scope: "report").size %>
</div>

app/views/posts/_vote_form.html.erb
<div id="vote_form">
  <% if user_signed_in? %>
    <% if current_user.voted_up_on? post %>
      <%= link_to post_vote_path(post,1), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-heart"></span>
      <% end %>
    <% else %>
      <%= link_to post_votes_path(post), method: :post, remote: true do %>
        <span class="glyphicon glyphicon-heart-empty"></span>
      <% end %>
    <% end %>
  <% end %>
  <%= t "posts.show.like" %> <%= post.get_upvotes.size %>
</div>

app/views/posts/edit.html.erb
<% provide :title, t("posts.edit.edit") %>
<% provide :button_text, t("posts.edit.save") %>
<div class="container">
  <h1 class="text-center"><%= t "posts.new.edit_post" %></h1>
  <%= render "posts/post_form", post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1><%= t "posts.index.post" %></h1>
  <%= link_to t("posts.new.add"), new_post_path, class: "btn btn-custom" %>
  <div class="row">
    <%= render @posts  %>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<% provide :title, t("posts.new.add") %>
<% provide :button_text, t("posts.new.create") %>
<div class="container">
  <h1 class="text-center"><%= t "posts.new.new_post" %></h1><br/>
  <%= render "posts/post_form", post: @post  %>
</div>

app/views/posts/show.html.erb
<div class="row show-post">
  <div class="col-md-4">
    <div class="row">
      <div class="thumbnail">
        <center>
          <div class="<%= "sold" if @post.closed? %>">
            <%= image_tag @post.post_img.url,
              class: "post-image #{'watermark' if @post.closed?}" %>
          </div>
          <div class="links btn-group">
            <% if can? :update, @post  %>
              <%= link_to t("posts.show.back"),
                posts_path, class: "btn btn-primary" %>
              <%= link_to t("posts.show.edit"), "",
                "data-toggle": "modal", "data-target": "#edit-post-modal",
                class: "btn btn-primary" %>
            <% else %>
              <%= link_to t("posts.show.back"), root_path,
                class: "btn btn-primary" %>
            <% end %>
            <% if can? :destroy, @post %>
              <%= link_to t("posts.show.delete"),
                post_path(@post), method: :delete,
                data: {confirm: t("posts.show.sure")},
                class: "btn btn-primary" %>
            <% end %>
          </div>
        </center>
      </div>
    </div>
    <div class="row">
      <% if user_signed_in? %>
        <div class="panel-body">
          <ul>
            <li><%= link_to @post.user.email, conversations_path(user_id: @post.user_id),
              remote: true, method: :post %></li>
          </ul>
        </div>
        <% if @conversation %>
          <ul id="conversations-list">
            <%= render "conversations/conversation",
              conversation: @conversation, user: current_user %>
          </ul>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6 col-md-push-1">
    <div class="post">
      <div>
        <center>
          <h2 class="post-title"><%= @post.title %></h2>
        </center>
        <h3 class="post-owner"><span class="glyphicon glyphicon-user"></span>
          <%= link_to @post.user.profile.name, user_path(@post.user_id) %>
          (registered <%= @post.user.profile.created_at %> ago)
        </h3>
        <h6 class="timestamp">
          <span class="glyphicon glyphicon-hourglass"></span>
          <%= @post.created_at.to_date %>
        </h6>
        <p class="post-tag"><%= t "posts.show.tag" %>
          <%= raw tag_list @post %>
        </p>
        <h4>$<%= @post.price %></h4>
      </div>
      <%= render "report_form", post: @post %>
      <h4><%= @post.impressionist_count %> views</h4>
      <%= render "vote_form", post: @post %>
      <% if can? :update, @post  %>
        <%= render "close_post", post: @post %>
      <% end %>
      <p class="post-content"><%= raw @post.content %></p>
    </div>
  </div>
</div>
<hr/>
<%= render "report_form", post: @post %>
<div class="row">
  <% if user_signed_in? %>
    <%= render "comments/comment_form", post: @post, parent_id: nil,
      comment_new: @supports.comment %>
    <%= render "posts/edit_post_modal", post: @post  %>
  <% end %>
  <%= comments_tree_for @supports.comments_tree.hash_tree(limit_depth: 3),
    @post, @supports.comment %>
</div>